### ISSUE TITLE
clientside encryption!!!

### ISSUE THREAD

**Issue by ericrange** [erming/shout#114]
if you implement clientside encryption... this would be an AWESOME project :OO
please do it!!

**Comment by JocelynDelalande** [comment]
+1 for OTR support (with key stored on the bouncer)

**Comment by astorije** [comment]
Yes, having OTR support in Shout would be terrific. That would definitely make the difference (well, another difference) with all other web IRC clients. So yes, in a way, you'd become "the next big thing in the IRC world" :p

**Comment by JocelynDelalande** [comment]
Work started, see #464
