### ISSUE TITLE
Running from a subdirectory

### ISSUE THREAD

**Issue by LouisKottmann** [erming/shout#158]
Hello,

This project interests me but I would need to run shout from a subdirectory i.e: `baboon.io/irc`

Is it already achievable? I didn't see any option for this.

I know you could do this with Kiwiirc but not Subway for example (other self-hostable webircs)

Regards,
Louis

**Comment by gurvindersingh** [comment]
+1

**Comment by ibizaman** [comment]
For future readers: I use haproxy on top of shout. That way I can make use of subdomains very easily!
