### ISSUE TITLE
Background Process

### ISSUE THREAD

**Issue by ghost** [erming/shout#170]
Hey!

One more feature suggestion!

I would love it if we could run shout as a background process, kind of like rails.

In rails you can run `rails server -d` which will start the rails server in the background, and you can end it by finding the PID and running `kill -9 PID`.

**Comment by astorije** [comment]
@ibizaman, could you send this as a PR please? It would be nice that, at `npm install` time, if `systemd` is available, the init script is installed as well. Then I guess others can come with their `upstart` script (for Ubuntu), `init.d` script (for Debian Wheezy, still supported until May 2018), ...

I am using [Supervisor](http://supervisord.org/) at the moment, but it's not idea, would be really nice to see this nicely packaged.

Thanks :-)
