### ISSUE TITLE
Better disconnect handling

### ISSUE THREAD

**Issue by erming** [erming/shout#235]
Right now, there's really no way to tell if you've been disconnected.

What I want to add:
- Better error messages
- Ability to automatically reconnect on disconnect

**Comment by fbm-static** [comment]
:+1:

**Comment by TheDoctorsLife** [comment]
+1

**Comment by richrd** [comment]
This would be awesome! :+1:

**Comment by nisargjhaveri** [comment]
Really need to have this.. Someone, please? ;)

**Comment by pheelee** [comment]
Reconnect would be wonderful. Some news about this enhancement erming?

**Comment by fbm-static** [comment]
:+1:
