### ISSUE TITLE
Subfolder

### ISSUE THREAD

**Issue by JQE** [erming/shout#243]
I am trying to figure out what would need to be changed to get shout to run in a subfolder instead of the root of the website. I want to put it behind an nginx reverse proxy.

**Comment by sigboe** [comment]
@erming Have you figured out how to do Apache reverse proxy? I do not understand either nginx or apache2 enough to translate @codl nginx settings to apache2. I am trying to figure it out even though :P Maybe I have to wait until #346 is merged.

**Comment by pheelee** [comment]
This would be great to be implemented.
My motivation is that I don't want to manage that much SSL Certs for all the subdomains
