### ISSUE TITLE
Shout crash after sometime with a Zlib error

### ISSUE THREAD

**Issue by mathieupoussin** [erming/shout#261]
I'm using a persistant shout process on my server.

I see that after sometime (random, it depend of a received message I suppose), shout crashes with this error :

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)
```

Nodejs 0.10.32
Shout 0.45.2

**Comment by josegonzalez** [comment]
@mathieupoussin did @erming's suggestion work for you?

**Comment by mathieupoussin** [comment]
I can't tell you, I don't have my shout setup anymore for now.

**Comment by erming** [comment]
This issue has been solved.
We're now using `request` instead `superagent` for fetching links, which solved this problem.

I'll close this.
