### ISSUE TITLE
Mobile notifications

### ISSUE THREAD

**Issue by janza** [erming/shout#265]
I was thinkint mobile push notifications could be useful for shout. 
Maybe using [pushbullet api](https://docs.pushbullet.com/)  api? Seems pretty easy.

What do you think erming?

**Comment by japesinator** [comment]
I've been looking at pushbullet a little bit over in https://github.com/japesinator/shout.  It isn't near ready to merge yet, but please let me know what you think

**Comment by janza** [comment]
@japesinator maybe a better place for API token would be user config instead of global config file?

**Comment by japesinator** [comment]
My fork can now send notifications on mention.  I still need to move the token location from the global config to user config and make sure the window is active, but I've confirmed it working with pushbullet.

**Comment by japesinator** [comment]
Looking at the issue @janza brought up, I don't feel comfortable with my API token in a cookie at the moment, but if [319](https://github.com/erming/shout/pull/319) gets merged, I would be more interested in moving the option over.  Still, imho, the API key should stay on the server as much as possible, and right now the client config is really, well, client-y.

**Comment by janza** [comment]
Sorry if it was unclear, I said it should be moved to user config, as in ~/.shout/user/xx.js (not the client). 
Otherwise it looks great!
