### ISSUE TITLE
Shout server stops everytime I close the connection to vps

### ISSUE THREAD

**Issue by Vlonjati** [erming/shout#335]
Hello,
I've installed Shout on a Virtual Private Server and I want to run there always. I start the server by doing: 
shout start (it starts on the port configured in config.js)
Everything is fine while I'm connected through ssh to my vps BUT when I close my connection to the vps Shout stops as well.
I want it to continue to run and accept connections from users.

Am I missing anything?

**Comment by Vlonjati** [comment]
Essentially I want it to run as a service like kiwiirc.

**Comment by janza** [comment]
I believe you want to use something like [pm2](https://github.com/Unitech/pm2) to demonize shout process: 

    pm2 start $(which shout)

Or you can just use screen or tmux and detach to keep shout persistent.

**Comment by erming** [comment]
I use `screen` myself.

The problem: When you disconnect, the session that runs Shout will exit.

However, if you were to use `screen`, you could fire up Shout in a screen session and that would keep it running even when you disconnect. You could think of it as a SSH session that never closes.

_If you want to try `screen`, here's a quick guide for you:_

Run this on your server via SSH:

```
sudo apt-get -y install screen
screen -S shout
shout start
# Now press CTRL+D (it should "detach" the screen)
# Done!
```

To open that screen again, type:
```
screen -x shout
```

**Comment by vohof** [comment]
I use `supervisord` for mine:

```
[program:shout]
command=node .
autorestart=true
directory=/home/shout/app
user=shout
stdout_logfile=syslog
stderr_logfile=syslog
environment=DEBUG="slate-irc",HOME="/home/shout"
```

**Comment by Vlonjati** [comment]
Thnx guys. All the solutions work :+1:
