### ISSUE TITLE
File Transfers (XDCC)

### ISSUE THREAD

**Issue by YeahToast** [erming/shout#340]
Any thoughts on adding xdcc to shout? I'd love that!! Some examples on node.js xdcc below.

https://github.com/pushrax/node-xdcc
https://github.com/Indysama/node-xdcc

**Comment by erming** [comment]
Sorry, I'm not going to implement this.

In my opinion, it's alot smoother to share files via Dropbox or any other service, so I'm not going to spend time implementing this.

Thanks for the suggestion though!
