### ISSUE TITLE
Pre-fetch links from chat messages

### ISSUE THREAD

**Issue by erming** [erming/shout#35]
Inspired by how Facebook handles links.

When someone posts a link, I want to pre-fetch that link and display information directly in the chat.

This could then be extended to work with:
- Thumbnails
- YouTube movie information
- GitHub info
- ...

**Comment by astorije** [comment]
[Telegram](https://telegram.org/) also does this wonderfully.
However, I am not too fond of using an external API for this...

@erming, this seems like it's done in current version (0.51.2), closing this issue to help with triage then. Feel free to re-open if I'm mistaken, but I feel like it's more relevant to open specific topic issues for this.
