### ISSUE TITLE
Instructions on how to run from source

### ISSUE THREAD

**Issue by jancborchardt** [erming/shout#355]
Hey @erming – great work on this IRC app!

I want to run it from source to contribute the odd design-enhancement. We also want to deploy it for @opensourcedesign. The instructions are only for installation via npm and my node knowledge is a bit spotty.

Can you enlighten me on how to run it from source? Would be cool if that dev/contributing setup is also in the readme. :)

**Comment by jancborchardt** [comment]
(You can find us in #opensourcedesign btw – we plan on deploying Shout so people can easily join our channel and design channels of other open source projects.)

**Comment by vohof** [comment]
```
git clone https://github.com/erming/shout shout && cd $_
npm install
node .
```

**Comment by jancborchardt** [comment]
@vohof https://github.com/erming/shout/pull/356
