### ISSUE TITLE
Change password in web interface

### ISSUE THREAD

**Issue by furier** [erming/shout#359]
Let users change password on the web user interface.

**Comment by fczuardi** [comment]
This is a very important feature, what would be the best place to include the change password form? The existing "Client settings" page?

**Comment by furier** [comment]
My educated opinion would be to create a separate tab as the current "Client Settings" and call it "User Settings" as they are two separate things or rename "Client Settings" to something more generic like "Settings". In a combined solution you would put up two "form" areas with their own heading saying "Client Settings" and "User Settings",

**Comment by fczuardi** [comment]
I have the same opinion, either another tab for user settings or a generic settings area, I am not familiar with the code, but I am interested in trying to hack a patch…

**Comment by fczuardi** [comment]
#63 is a related, if that gets fixed maybe we can merge the 2 issues, or break #63 into separated smaller tasks in which this one is one of them

**Comment by furier** [comment]
Sounds good 😄

**Comment by kalaksi** [comment]
A big +1 to this. Any information about any progress? I'd be glad to help as I'd definitely like to see this feature. Btw, I agree about how it should be on the UI.

**Comment by lizardsrock4** [comment]
+1  Allowing users to change their passwords so they don't have to trust the host with it would be great

**Comment by TheDoctorsLife** [comment]
+1 I let several people use my instance of shout, letting them change thier password is a must.

**Comment by MaxLeiter** [comment]
This was added to Lounge in thelounge/lounge#57
