### ISSUE TITLE
Feature Request: Click on Channel Links

### ISSUE THREAD

**Issue by shadowfacts** [erming/shout#361]
Suggestion:
If someone types a channel name in chat, the user should be able to click on it from the web interface and automatically join the channel. e.g. If someone typed #minecraftforge, on the web client #minecraftforge would appear as a link, and when clicked on, shout would join #minecraftforge for them.

**Comment by erming** [comment]
Agree!

This shouldn't be too hard to implement. I'm already scanning every message for links. It could also scan for `#chan` and make them clickable.

**Comment by shadowfacts** [comment]
Sounds Good :smile:

**Comment by xPaw** [comment]
This was fixed.

**Comment by astorije** [comment]
Indeed, fixed in #385, thanks for the triaging help! :-)
