### ISSUE TITLE
Individual Channel/Network Options

### ISSUE THREAD

**Issue by HuggableSquare** [erming/shout#381]
It would be nice to have options for specific channels/networks for things like showing joins and parts and link previews.

For example, when using Twitch chat in an IRC client (as I sometimes do) it shows joins and parts in massive blocks instead of in real time, and as such it can be obnoxious to see these blocks, but I would like to keep them on for other networks or channels.

Another example is, specific links don't load well in the preview, and so I'd like to turn them off for specific channels where I know these links will be used alot, but I'd like to keep them on for other channels where it isn't an issue.

I know this may not be a tier one issue, but it is one that has me on the fence about switching over from HexChat.

**Comment by erming** [comment]
I've connected to Twitch IRC, it's crazy!

But I'm not sure about this one. It would require overhauling the current settings handling. There would have to be some kind of "general" settings and then network-specific settings, which would have to override these settings.

I'm not saying it's impossible, but I think it would cost too much time fixing this request. I'm a fan of keeping it simple – maybe it's worth tinkering on the join/part instead (some kind of "spam control").

See: https://github.com/erming/shout/issues/48

Also, yes, the preview is a bit funky. Not sure what I should do about it right now..

I will close this issue.

But thanks! Feedback is always appreciated.
