### ISSUE TITLE
Make it possible to disallow Joining & Leaving of Channels

### ISSUE THREAD

**Issue by bnvk** [erming/shout#384]
I have a use case where I need to setup an instance of Shout as a chat environment / portal to a community of users that are not very technical. The spec from the community asks to "Make the using of IRC extremely simple and fool proof to use." Basically, what this community wants & needs is a "Slack that works on top of IRC"

The idea is to expand upon UI facing things such as #380 which hides / makes network display configurable. Thus, I am going to implement a `channelsActionable` flag to the config that does the following:

- [x] Add variable to config.js
- [x] Hides the **channels** field on connecting
- [x] Hide the "X" button to leave a channel from the sidebar
- [x] Hide the "Leave" button in the room header
- [ ] Allows & disallows typing the `/join` and `/close` commands from user inputs

I *think* this is a broad enough use case that it will be desirable beyond my use case... I hope so at least :smile:

**Comment by jancborchardt** [comment]
Good call! Maybe instead of hiding the channels field completely just disable it? Then people still know what they will join. Also because those channel names will show up in the sidebar then anyway.

**Comment by bnvk** [comment]
@jancborchardt yah, the channels will all show up on the sidebar after joining... hrm lemme think about that about that UI wise... "You're about to join #chan1, #chan2, #chan3" interesting

**Comment by bnvk** [comment]
Despite implementing what I was hoping to- I'm going to close this issue as my solution feels far too kludgy now that I better understand the codebase. I created a new issue #387 which brings up what I was hoping to achieve here!
