### ISSUE TITLE
Connect using parameters from form

### ISSUE THREAD

**Issue by ircer** [erming/shout#394]
Hi

I want to change our website from our current Flash IRC client to Shout but I have a question.

At the moment we use a HTML form where the user enters a nickname etc. which gets passed to the Flash IRC client so the user doesn't see it's standard 'login form'.

Is it possible with Shout?

i.e. to skip the start screen, use the nickname, channel (hidden form field), server (hidden form field) etc. from our form so the user doesn't see it?

Cheers,
Jack

**Comment by erming** [comment]
Hmm. There's no built-in way to do this, no.

But with a little bit of frontend javascript magic you could probably trigger the connect form upon page load.

_Something like this might work:_ 

```
socket.on("init", function() {
  $("#connect form").submit();
});
```

Try adding that snippet to the last line of the jQuery ready function in `client/js/shout.js`. Before the brackets close, right here: https://github.com/erming/shout/blob/master/client/js/shout.js#L880

Then you can tweak the default server, port, nick etc. by messing with your `config.js`-file.

Good luck!
I'll close this issue, but feel free to ask if there's anything more.

**Comment by ircer** [comment]
@erming so should I set the HTML form to submit to `client/index.html`?
