### ISSUE TITLE
displayNetwork is undefined error crashes shout

### ISSUE THREAD

**Issue by parliament718** [erming/shout#398]
I had shout working this morning but all of a sudden I start getting this error:

![shout-error](https://cloud.githubusercontent.com/assets/3580270/7153111/1d5cab06-e315-11e4-9aaa-00a2228906ed.PNG)

It errors out when I navigate to localhost:9000. I actually just pulled a fresh copy to make sure it wasn't something I accidently modified, but I get the same problem on a fresh clone.

**Comment by erming** [comment]
Okay, thank you for reporting in. I will take a look at this later today. It's from a recent pull request I've not really tested thoroughly.

For the time being, try removing your old config (probably located at `~/.shout/config.js`) and restart Shout. That should fix the problem I think.

**Comment by erming** [comment]
Hello again!

This bug has now been fixed in the latest version (https://github.com/erming/shout/commit/7138ca6bda5430d1fdbc9f6e530d9cfd11247bd1).

I'm closing this issue.

Thanks!
