### ISSUE TITLE
Kick reason isn't showing

### ISSUE THREAD

**Issue by hashworks** [erming/shout#404]

**Comment by xPaw** [comment]
Quit reason isn't showing either. I will look into fixing it in #588

**Comment by xPaw** [comment]
Okay, for this to work, `slate-irc` library needs to be updated to 0.8.1.

**Comment by astorije** [comment]
Thanks @xPaw!

**Comment by YaManicKill** [comment]
This wasn't actually fixed in that PR, was it?

**Comment by xPaw** [comment]
It was, but it also required updated `slate-irc`.

**Comment by YaManicKill** [comment]
Ah yes, that was a different PR, wasn't it?
