### ISSUE TITLE
<Tab> button replacement for mobile

### ISSUE THREAD

**Issue by hashworks** [erming/shout#406]
On mobile you mostly won't have access to a tab button, so you can't autocomplete nicknames.

**Comment by erming** [comment]
I've not found any way to solve this easily without adding some kind of overlay/suggestion-thingie for the autocompletion plugin, which I think is alot of job to do.

And I'm sorry, but I'm probably not going to fix this right now. I'll close this issue. I hope missing out on tabcompletion doesn't annoy you too much.

Thanks

**Comment by hashworks** [comment]
The app AndroIRC solved this by adding a clickable icon before the input element which calls the autocomplete function, I think it's a good solution.

**Comment by erming** [comment]
Yeah, that wouldn't be that much work to implement. All it would need to do is trigger a "tab" event on the input field.

But do you think it's obvious what such a button would do? Thinking about the user experience (UX) here. It might just be confusing (but I'm not sure, never tried anything like it).

**Comment by hashworks** [comment]
The app was using a question mark, indicating search. Not sure if there is a more obvious simbol, I'll think about it.

**Comment by richrd** [comment]
One solution (on Android) is to install Hackers Keyboard. I've been using it for a long time and it solves all  problems of this kind. https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en
