### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by tjfwalker** [erming/shout#410]
The message input doesn't currently provide spelling error highlighting/underlining/annotation.

[ FF Dev, OS X 10.10.3 ]

**Comment by erming** [comment]
I've turned this off on purpose. I'm personally not very fond of spellchecking. It just annoys me when I switch between my native language and english, and don't think it's that big of a deal to miss out on this.

Related: https://github.com/erming/shout/blob/master/client/index.html#L280

I'll close this issue, but thank you for showing interest!
