### ISSUE TITLE
Feature Request: Username mentioned Window

### ISSUE THREAD

**Issue by McGriddle** [erming/shout#421]
For people that leave shout on for long periods of time (because it's amazing), it would be nice to track comments that mention your username. Maybe this would be more of a plugin once that is supported but I thought this would be nice:
- Have a window per network that tracks mentions of your set username.
  - one or  two messages before and after said comment for context
  - A link to easily navigate to the comment mentioned

**Comment by fbm-static** [comment]
This is the reason I went back to using ZNC. I just use shout as the IRC client which has a nice UI. Even if this gets implemented, the messages have to be stored into a file for it to be persistent.

**Comment by sc0tt** [comment]
:+1:
