### ISSUE TITLE
Shout with NGINX server

### ISSUE THREAD

**Issue by YugiFanGX** [erming/shout#428]
I installed shout sucessfully. My problem is that I am running NGINX on the same server, but I would like to use Shout on a Subdomain. I tried to forward the port 80 to something like this inside nginx settings:
	location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://127.0.0.1:9000;
    }

How can I run nginx and shout at the same time?

**Comment by derhuerst** [comment]
Can you post how do did it just to help users who may have the same problem at some point?

**Comment by YugiFanGX** [comment]
I removed 
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $http_host;

restarted nginx and used Tor Browser instead, which does not cache the site. Was a simple fix.

**Comment by TheDoctorsLife** [comment]
Another solution I've found is to use ```    location / {
        proxy_pass https://127.0.0.1:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }```

**Comment by TuSuNaMi** [comment]
Any fix ?

**Comment by k0nsl** [comment]
@TuSuNaMi 

This is the configuration I am currently using for my [web IRC](https://webirc.k0nsl.org/) (Shout):

```text
server {
        listen   98.158.134.62:80;
        listen [::]:80;
        server_name webirc.k0nsl.org;

        access_log /dev/null;
        error_log /dev/null crit;

location / {
        proxy_pass http://98.158.134.62:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
}
}
```
That is a very basic configuration but it does what it is supposed to do :)
Best wishes,
-k0nsl

**Comment by astorije** [comment]
@TuSuNaMi, @k0nsl, I also strongly suggest you add HTTPS support to this. It was briefly documented in this project's wiki but the wikis have apparently been disabled. It can still be found on our community fork wiki: [Enable HTTPS with Let's Encrypt](https://github.com/thelounge/lounge/wiki/Enable-HTTPS-with-Let%27s-Encrypt).

**Comment by YaManicKill** [comment]
And if you want to add https with nginx:

server {
    listen 443 ssl;
    server_name irc.10people.co.uk; # Replace with your domain

    ssl_certificate /etc/letsencrypt/live/irc.10people.co.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/irc.10people.co.uk/privkey.pem;

    location / {
        proxy_pass https://localhost:9000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }
}

Although, mind you, that won't forward http to https, it'll just fail if you go to http.
