### ISSUE TITLE
Allow something to be said automatically when connecting to a server

### ISSUE THREAD

**Issue by tucker-m** [erming/shout#437]
I'm thinking specifically of `/msg NickServ identify password`. 

Having Shout running on a server that always stays on is nice -- however, it's been disconnected a few times, so I need to re-identify with NickServ when I start it up again. I think it'd be useful if, in each user's config file, they could specify something to say when connecting to a server. Many IRC clients support some kind of "auto identify" feature like this.

**Comment by lizardsrock4** [comment]
I would love this, I don't sign out very often, but this would be helpful for when I do

**Comment by fnkr** [comment]
+1

**Comment by fnkr** [comment]
This is already implemented.

Usage:
```
		"commands": [
			"/msg NickServ identify password",
			"/msg ChanServ op #chan"
		],
```

See https://github.com/erming/shout/issues/78.

**Comment by tucker-m** [comment]
Oh, nice! I wasn't aware of that. Thanks!
