### ISSUE TITLE
How to modify.tpl Files

### ISSUE THREAD

**Issue by anonprophet** [erming/shout#439]
i want modify ``chat.tpl`` and ``chan.tpl`` in ``/client/views``

when i modify these files, refresh browser or restart shout

there are no chanage happen,.

**Comment by Fidelix** [comment]
You have to restart the NodeJS server for the changes to apply

**Comment by astorije** [comment]
It is very likely that you also need to run `grunt` to apply your changes to the rendered templates.
As this is a **support case** more than an issue, next time I advise you to ask your question on the `#shout-irc` channel and chances are you'll get an answer very quickly there :-)

I am closing this, let me know if I misunderstood.

**Comment by floogulinc** [comment]
You need to run `grunt` to build those files into the template JS.
