### ISSUE TITLE
Hello anybody here?

### ISSUE THREAD

**Issue by devalnor** [erming/shout#444]
This great project seems to be in sleeping mode since more than a month.
Lot of pull requests and issues are waiting answers.

So it's just a question before in dive into this project:

Anybody here ?

Regards,
Mx

**Comment by evertheylen** [comment]
It's a very nice project indeed, but it could really use some more work. I would like to contribute as well, but my experience with complex javascript apps is very limited.

However, perhaps the devs are just taking some vacation? I do applaud your effort though :+1:.

**Comment by astorije** [comment]
@devalnor, @evertheylen, I can tell you that Shout is being loved again :-)
Stay tuned and feel free to send us your love through PRs!
