### ISSUE TITLE
Displaying Notification of new Messages in Tab

### ISSUE THREAD

**Issue by Z3roCoder** [erming/shout#446]
Something like just a hint that new messages arrived would be useful, as well as getting that strange Desktop-Notification thing to work. I activated and allowed it, but no Notifications are coming through.

**Comment by nickel715** [comment]
I had the same problem, notifications only works for messages wich highlights me. 

My dirty fix to get notifications for all messages is to change the line 576 in shout.js to:

    if (highlight || isQuery || true) {
