### ISSUE TITLE
User list

### ISSUE THREAD

**Issue by ircer** [erming/shout#450]
I am switching our website over to Shout from our current Flash client. Can someone please show an example of how I can colour nicknames based on their username (username@)?

**Comment by astorije** [comment]
Hi @ircer,

If I understand your question properly, this is a **support case**. For those, feel free to ask your questions on the #shout-irc channel and you'll be likely to have an answer right away.

To answer, first go to your settings by clicking on:
<img width="121" alt="Icons" src="https://cloud.githubusercontent.com/assets/113730/10114785/7f7c9400-63f7-11e5-89b2-5d2e5ad3cf24.png">

Then, check "Enable colored nicknames":
<img width="451" alt="screen shot 2015-09-26 at 02 35 29" src="https://cloud.githubusercontent.com/assets/113730/10114798/b0d772cc-63f7-11e5-9ece-6ddc2c794165.png">

Users will then appear like this:
<img width="138" alt="User list" src="https://cloud.githubusercontent.com/assets/113730/10114795/a71bd5d4-63f7-11e5-8946-0428f2d68f89.png">

I am closing this issue, please tell me if I misunderstood and I'll reopen.
