### ISSUE TITLE
Chat clear keybinding conflict

### ISSUE THREAD

**Issue by Henni** [erming/shout#453]
Modern browsers offer the keybinding `Ctrl + L` to select the location bar.
Shout implements this shortcut to clear the chat history since #165.

Maybe this shortcut should be changed or the browser action should be prevented.

**Comment by astorije** [comment]
Any suggestion here? Lacking one, I think removing this shortcut seems to me like the right way to go at the moment...

**Comment by JocelynDelalande** [comment]
> I think removing this shortcut seems to me like the right way to go at the moment...

Either that or binding it to something else (ctrl+shift+l) seems best option to me at the moment.
