### ISSUE TITLE
Shout closes IRC session on tab close

### ISSUE THREAD

**Issue by txomon** [erming/shout#457]
Hi!

I have installed the last version from npm, and when I close the shout tab, the IRC session is closed. What am I doing wrong?

**Comment by txomon** [comment]
Moreover, If I open in another windows the shout url, I will have to login again

**Comment by lizardsrock4** [comment]
Do you have logging enabled for that account?

**Comment by txomon** [comment]
There is no account. I set up public shout with basic auth for me.

**Comment by richrd** [comment]
If I recall correcly, you need to setup an account to get shout to maintain the IRC connection. (Am I right?)

**Comment by erming** [comment]
Yes, that's correct @richrd.

@txomon When connected as "Guest" the connection will close when you close your tab/browser. If you want to stay connected when you close you need to have a user setup.

You probably know how to add users, but here's a link to the docs: http://shout-irc.com/docs/server/users.html

There's curretly no support for both users AND public (I usually solve it by running two instances of Shout on two different ports).

Good luck!

**Comment by txomon** [comment]
Oh ok, would it be possible to mention the fact that guests are not
supposed to be permanent? May seem obvious from the inside but I just
thought you meant another thing at the end. =)
