### ISSUE TITLE
Allow explicit config location

### ISSUE THREAD

**Issue by harrislapiroff** [erming/shout#461]
It would be awesome if you could explicitly give a location for your config files when starting Shout. This would allow users to run Shout in environments where you can't count on the `HOME` variable to be set and would allow users to experiment with/alternate between multiple configurations.

I imagine two possible interfaces for this (which are not mutually exclusive).

1. Check for an environment variable `SHOUT_CONFIG_DIR`.
2. Have an option on the CLI command, e.g., `shout --config-dir ~/configurations/shout`

**Comment by astorije** [comment]
@harrislapiroff, if I understand your request properly, this can already be done: http://shout-irc.com/docs/server/configuration.html#home.

I am myself using that option [when starting Shout with Supervisor](https://github.com/astorije/ansible-role-shout/blob/860ce54e97c5562de9b96c6f47aac11fb5bc4c68/files/shout_supervisord.conf#L2).

**Comment by astorije** [comment]
@harrislapiroff, can you confirm that the `--home` option is what you are looking for?
I will be closing this issue and mark it as `wontfix` should this lack additional information from you.

**Comment by harrislapiroff** [comment]
Yeah, that looks like what I am looking for! Not sure why I didn't see it before. I ended up setting a value for the env `HOME` in my supervisor config, but that's more elegant.
