### ISSUE TITLE
Fix failing build

### ISSUE THREAD

**Issue by astorije** [erming/shout#466]
Badges added in https://github.com/erming/shout/pull/465 emphasize that the Travis CI build is currently failing. This is a friendly reminder to fix that.

**Comment by floogulinc** [comment]
We fixed this with PonyChat/Shuo#31

**Comment by astorije** [comment]
Hum, are you sure @floogulinc?

The error on https://travis-ci.org/erming/shout/builds/49741250 says:
> Error: Cannot find module '/home/travis/.shout/config'

I'm not saying your commit would not fix another issue on Travis CI, but this one doesn't seem related to your fix.

**Comment by floogulinc** [comment]
Ah, I forgot the first part of the fix we did. Here: PonyChat/Shuo@fe9752516e29d27bf2bbd53f2b612b962b296890

**Comment by astorije** [comment]
Yep, either that or at install time, but at least storing that in the Travis CI configuration it stays somewhere where shame is visible :-)
