### ISSUE TITLE
Publish version 0.51.2 to npm!

### ISSUE THREAD

**Issue by astorije** [erming/shout#472]
[Shout 0.51.2](https://github.com/erming/shout/releases/tag/0.51.2) was tagged yesterday but not sent to [npm](https://www.npmjs.com/package/shout) :-(
Please `npm publish` it!

You might also want to enable [automatic publication through Travis CI](http://docs.travis-ci.com/user/deployment/npm/) (but #466 needs to be fixed before, at least with the merge of #469). Example [here](https://github.com/astorije/chai-immutable/blob/5908ecbd879f5fe8c829fc50e83b2c88496d8576/.travis.yml#L8).

**Comment by erming** [comment]
Done!
