### ISSUE TITLE
Set up AppVeyor CI

### ISSUE THREAD

**Issue by astorije** [erming/shout#480]
[AppVeyor](http://www.appveyor.com/) is the Windows equivalent of Travis CI. Even its configuration seems to be really similar to it.
I know that there is no documentation for Windows yet, but since it's running on Node.js, I don't see why it should not work... And if it doesn't, AppVeyor should tell us why :-)

**Comment by JocelynDelalande** [comment]
@astorije Ok with it if we have someone using windows around for helping/taking care of fixing things if broken, otherwise I'm against trying to maintain things out of our reach/knowledge.

For example, I have almost zero windows OS knowledge, and would be incapable of debugging a windows behaviour.

**Comment by astorije** [comment]
I disagree. This ticket is not called "Add support for Windows". It simply creates another source of reports that we'll be happy to have. Nothing forces us to support Windows if we decide to enable a tool.
Oh and we do have Windows users.

Finally, it's a preventive measures: when client tests show up in Shout, they **will** need to be tested on different browsers and different OSses.

Anyway, this will come for free on our side, I don't want to debate the cost of free as that time would come as a cost...

**Comment by astorije** [comment]
Closing this. I am still in favor of having multiple CI environments, but 1) there is nothing to test against a the moment, 2) if I ever find a bit of time to contribute on Shout, I'd rather do some actual code rather than polishing the bike shed.
