### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by williamboman** [erming/shout#485]
Would be nice to have a consistent coding style throughout the project. Enforcing it is done using tools like `eslint`, `jshint`, `jscs`. Having an `.editorconfig`<sup>1</sup> file would help to seamlessly enforce parts of it.

-
<sup>1 - #74, http://editorconfig.org/</sup>

**Comment by JocelynDelalande** [comment]
@williamboman sure, good idea, could help to check style on PR automatically as well. I have no knowledge into those things in js-world, but would be happy to learn reviewing a PR ;-)

(obviously, try to match the existing standards over your personal preferences, of course)

**Comment by williamboman** [comment]
@JocelynDelalande Opened a PR.
