### ISSUE TITLE
Question about enabling access to client from outside of host device

### ISSUE THREAD

**Issue by Adam24** [erming/shout#495]
matt, how do I enable public mode so I can access it from my public IP?

**Comment by nickel715** [comment]
This very depends on your system. The easiest way is to open the port (which is configured in config.js) in the firewall.
Another way: if you have a webserver on your server you can add a rewrite rule, then you have not to open the port. This blog post describs how to do it with apache: https://stefanzweifel.io/posts/shout-on-uberspace/

**Comment by astorije** [comment]
@Adam24 I am closing this as the right place to ask questions is the #shout-irc channel. Feel free to ask it there if you are still blocked. I hope you found a solution, in which case posting it here would help those who end up here in the future.

Thanks!

**Comment by matikbird** [comment]
Has anyone found a solution to this?

**Comment by dgw** [comment]
@matikbird You may wish to switch to Shout's community fork, [The Lounge](https://github.com/thelounge/lounge), which is under active development. Shout's development has stalled.

**Comment by matikbird** [comment]
I know, it's written everywhere, @dgw 
But I'm fine with Shout.

I just want to know that.. because with KiwiIRC that doesn't happen. And with lightIRC (a flash client), doesn't happen either.

Why you've had choosen going for a proxy instead the host of the user?

**Comment by MaxLeiter** [comment]
The reason people use Lounge is your questions have a high chance of being answered
