### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by pingpong1109** [erming/shout#498]
I try running this command:

*sudo apt-get -y install nodejs-legacy npm*

and I get this error:

*The following packages have unmet dependencies:
 nodejs-legacy : Depends: nodejs (>= 0.6.19~dfsg1-3~) but it is not going to be installed
 npm : Depends: nodejs (>= 0.6.19~dfsg1-3) but it is not going to be installed
       Depends: nodejs-dev
       Depends: node-request but it is not going to be installed
       Depends: node-mkdirp but it is not going to be installed
       Depends: node-minimatch but it is not going to be installed
       Depends: node-semver but it is not going to be installed
       Depends: node-ini but it is not going to be installed
       Depends: node-graceful-fs but it is not going to be installed
       Depends: node-abbrev but it is not going to be installed
       Depends: node-nopt but it is not going to be installed
       Depends: node-fstream but it is not going to be installed
       Depends: node-rimraf but it is not going to be installed
       Depends: node-tar but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.*

**Comment by Xe** [comment]
This is a problem with your Debian/Ubuntu install and not Shout itself. Please contact the appropriate support channels.

**Comment by JocelynDelalande** [comment]
@pingpong1109 you may want to try https://github.com/nodesource/distributions#deb
