### ISSUE TITLE
Image preview size limit

### ISSUE THREAD

**Issue by olivierlambert** [erming/shout#500]
Today, my colleague pasted a direct link to a very large image ([this one](http://www.nasa.gov/sites/default/files/thumbnails/image/crop_p_color2_enhanced_release.png)). The preview should be limited for large files and displayed only if confirmed (maybe with a message like this: "This picture is larger than 10MB, click to preview").

**Comment by JocelynDelalande** [comment]
@olivierlambert thanks for taking time to report, you're right, any skills to submit a PR ?

**Comment by olivierlambert** [comment]
Maybe :) Can you point me to the right place in the code? (to be efficient)

**Comment by olivierlambert** [comment]
Here? https://github.com/erming/shout/blob/2cee0ea6ef5ee51de0190332f976934b55bbc8e4/src/plugins/irc-events/link.js#L86

**Comment by JocelynDelalande** [comment]
@olivierlambert yes, I think you found it :)

the template on client-side is here : https://github.com/erming/shout/blob/e0e20e5eefafa206d6214a4ce3d46ed2d85a9bb0/client/views/toggle.tpl

**Comment by olivierlambert** [comment]
I think I will start easy in the first place: do not make a preview for image larger than a certain size. On this topic, any idea? 1MB? More, less?

**Comment by JocelynDelalande** [comment]
@olivierlambert I would go for 512kB and make it configurable.

**Comment by olivierlambert** [comment]
Done: https://github.com/erming/shout/pull/503

**Comment by olivierlambert** [comment]
@JocelynDelalande : the PR is updated, it works even if you don't have the new value in the config file (default: 512kb), and the filter/condition is now only applied on images.

The ultimate step would be to see only a grey thumbnail indicating "Too big to be displated", but that's more a cosmetic issue: it works as expected thanks to this PR.

**Comment by astorije** [comment]
Merged, will be in the next release of Shout, thanks!
