### ISSUE TITLE
Does not use the config.js I made

### ISSUE THREAD

**Issue by pingpong1109** [erming/shout#505]
I have done shout config and changed the file and put a script in /etc/init.d to run at boot but whenever that run it doesn't use my config file.

**Comment by Xe** [comment]
Please be sure the user account matches what you think it does

**Comment by pingpong1109** [comment]
What do you mean?

**Comment by Xe** [comment]
in your init script, make sure it's running as the correct user.

**Comment by JocelynDelalande** [comment]
@pingpong1109 so ?

**Comment by pingpong1109** [comment]
ok thank you

**Comment by JocelynDelalande** [comment]
@pingpong1109 please, when asking for support on an issue tracker, at least, give feedback about your issue resolution, it can be as simple as 

> "oh yes, thanks, indeed I was running with user foo but the config file was in */home/bar/.shout/config.js*."

That way, the time spent by volunteers on their free time to answer you will be valuable for other people crawling the web or the bug tracker with similar issues.
