### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by olivierlambert** [erming/shout#510]
Hi lads,

It seems there is a lot of PR's on the way, but I can't evaluate if the project is still moving (no "active" dev branches, no status somewhere, no blog)

I can help somehow on various topics (e.g starting by [my PR pending](https://github.com/erming/shout/pull/503)), but I can also help on organizing some stuff. I'm the project leader on a reasonable fullstack JS project ([Xen Orchestra](https://github.com/vatesfr/xo)), so I think I could use this experience for this project.

I am myself using Shout everyday, and I'm sincerely ready to help for avoiding a lot of people "killing IRC" by getting on proprietary solutions like Slack/HipChat/whatever.

Warning: I'm more a project manager than an JS expert, but I know that organizing a project is really important. And we got enough good developers here I think ;)

Anyway, it would be great to:

1. discuss with active users/contributors how to organize a better basic communication
1. have a contributing file

The other things will come "naturally" (more tests for better PR's integration etc.)

Finally, the original question: what is the current shout status?

**Comment by floogulinc** [comment]
AFAIK, until recently, Shout was rather stagnant (the reason [Shuo](https://github.com/Shuo-IRC/Shuo) was created). But now development seems to have started up again with some new contributors. We are pretty much doing everything in the master branch and the dev branch seems dead.

**Comment by olivierlambert** [comment]
@floogulinc : any chance to merge those 2 projects in one to avoid community fragmentation?
@erming : what about your opinion on that?

**Comment by floogulinc** [comment]
@olivierlambert I have been making PRs for pretty much every feature and fix we add to Shuo (though most remain unmerged) as well as merging new PRs and features from Shout into Shuo. We are planning on possibly doing a full remake of Shuo, probably not in Node, at some point. So when that happens we will most likely stop working on the current Shuo and try to merge our features into Shout.

**Comment by olivierlambert** [comment]
@floogulinc that's good news: so we just have to got Shout to be active again!

**Comment by niedzielski** [comment]
[Kiwi IRC](https://github.com/prawnsalad/KiwiIRC), as an active web IRC project, might be worth a mention as well, although I'm not sure what opportunities exist for collaboration.

**Comment by Xe** [comment]
@olivierlambert we'd love to merge the two efforts into one, however there is a move on our end to start a complete rewrite of how the core works to avoid a lot of the inefficiencies, insane libraries and make it much faster.

**Comment by olivierlambert** [comment]
@xe: you speak for the fork (Shuo) I suppose?

**Comment by Xe** [comment]
@olivierlambert Yes, I should have been more specific. The core library that is used to connect to IRC (Slate IRC) is very lacking in some critical levels that have left Shout actually seeing an incomplete representation of the server state that is very clearly sent and easily understood. After doing intensive investigation into all aspects of the program, we've concluded that the only reasonable thing to do is to start on a clean room rewrite of the backend.

We're still in the thinking things over stage. I think that a good place to start is going to be using [Go](http://golang.org) for the core and extend it with [Lua](http://lua.org) or by subprocess communication using a hooking methodology.

**Comment by JocelynDelalande** [comment]
@olivierlambert Hi, as you may have noticed, we are in the process of resuming shout from sleep :) (had sadly been idle for couple of months before that).

@erming recently opened the maintainer's door to @astorije and me (for the moment), to turn it into something more collective… and less [bus damages-prone](https://en.wikipedia.org/wiki/Bus_factor).

The three of us are going to communicate more formally soon, for now we try to put some order and awake the beast gently, but we can already say shout is back on track :-). 

For now we are busy trying to establish some basic working rules and do the triaging/reviewing work (and well… trolling, at times ;-)).

Regarding shuo, from what I got chatting with @Xe and @floogulinc I think we all agree merging efforts is a good move, and in fact, @Xe and @floogulinc are always here to help (thanks !).

**Comment by olivierlambert** [comment]
Okay, as I said, I'm more efficient for everything around a project, like organizing releases (milestone, triage, prioritizing), making specifications, bug reports, blog posting and social media stuff than writing actual code.

However, I'll try to make my best on my existing PR.

**Comment by astorije** [comment]
Salut @olivierlambert!

Thanks for offering your help! Triaging issues and PRs takes an awful lot of time, to the point where I am currently stopping all code on Shout until we reduce open tickets.

If you want to help, a few suggestions:
- Sit on the #shout-irc channel: it is always very helpful to answer support questions from users who asking for help. Another idea is that all developers on the channel are discussing, sometimes about going towards different directions. Recording ideas and making sure we stay in line with the actual project would be priceless, as it's too easy (and often for open source projects) to focus on silly things and forget the core value
- Go over open issues and PRs: it can be a simple hello on tickets wondering if there is life here (like yours :) ), a few questions to the author, or a full review as @JocelynDelalande and I are trying to do whenever we can
- Feed [the roadmap](https://github.com/erming/shout-roadmap), which is currently empty, with what gets discussed and gathered on the IRC channel and the open tickets.

Hope that helps, let us know if you have any questions.
In the meantime, good luck with your PR!

(Marking this as `wontfix`, and we'll probably close this issue soon with your approval)

**Comment by olivierlambert** [comment]
Thanks for your answer @astorije 

Closing issue after all my questions were answered :D

**Comment by astorije** [comment]
Hey @olivierlambert, going back to you about offering to drive parts of this project. As a matter of fact, we are in desperate need of help to make sure Shout can grow nicely. I don't know if you are on the #shout-irc channel at the moment, so here is what I just posted there:

> 18:13	**&lt;astorije&gt;**	I think it's past time we think of a good plugin system for Shout so that it can nicely handle our numerous contributions, testability, maintainability, evolutivity, ...
> 18:13	**&lt;astorije&gt;**	However, it's a rather complex project, that needs design before jumping in
> 18:14	**&lt;astorije&gt;**	What would be terrific is if someone here would be willing to drive this project
> 18:15	**&lt;astorije&gt;**	This means, IMO:
> 18:15	**&lt;astorije&gt;**	- writing down the requirements (which are already started here: https://github.com/erming/shout-roadmap#plugin-mechanisms)
> 18:17	**&lt;astorije&gt;**	- drive the discussions around these requirements, make sure that a bunch of people (ideally those already contributing on Shout, but that could also be external folks having designed well working plugin systems) is giving their opinion before coding anything
> 18:18	**&lt;astorije&gt;**	- syncing with the core maintainers (@erming, @JocelynDelalande, @floogulinc and/or myself) as these discussions evolve, although I'm pretty sure we'd hang out where the discussions happen anyway
> 18:19	**&lt;astorije&gt;**	- Ideally, once we know where we're going, split the work into tasks that can be spread (or not) among those who are willing to write actual code (myself included)
> 18:21	**&lt;astorije&gt;**	Driving this does not mean coding it, although I'm sure if someone gives enough love to discussing a project, it's also to be a part of its implementation :) But again, nothing is mandatory here, having clear requirements and steps to achieve them would be tremendous as future folks could take up one of these if they want to contribute
> 18:21	**&lt;astorije&gt;**	I know it's a long shot for me to ask that, but it's vital for Shout and also important enough to require multiple people to give their feedback before throwing code at it
> 18:26	**&lt;astorije&gt;**	Anyway, if someone wants to (thinking of @olivierlambert if he is still around, as he offered it here: https://github.com/erming/shout/issues/510#issuecomment-145683059), they know where to find me! :)

Anyway, any help would be awesome, but even feedback and suggestions help. Thanks in advance! :-)

**Comment by olivierlambert** [comment]
Hi @astorije 

I wasn't on the channel so thank you for the recap here.

First thoughts:
* I have some feedback/experience to offer, I'll write a blog post about how we managed to drive a project on GitHub (Xen Orchestra). I'll keep you posted ASAP here, should be written soon. I think it could be very helpful in the Shout case (giving hints, best practices, issue tags usage etc.) Also how I see things, to check if it fits for current Shout maintainers.
* I don't have an infinite amount of time to offer, but I think giving some push on the "right" direction could help a lot here (structuring the process etc.)

So I'll be glad to help in this role, as far as I can.

**Comment by astorije** [comment]
Hi @olivierlambert,

Thanks for your answer and very sorry for the lack of answer on my side. As you can see I can get very busy, which is why this contribution will definitely help.
Shout is in desperate need for a plugin mechanism to ensure parts of it can evolve at different paces, with different sets of people maintaining them.

Would you be OK to start driving the requirements and discussions on this? It's crucial we get to a point where we know what we want, so that some of us can start to actually implement them. As you move along with the requirements, people including myself will jump in to suggest and/or contribute to them, so really the start is the difficult part.

I don't know what's the most efficient to produce requirements, but I would say either a PR or a wiki page on https://github.com/erming/shout-roadmap will do. Discussions can happen on IRC and/or email. Let me know if you have any questions/suggestions and I'll try to get back to you much faster next time.
It would be nice to have something (reqs, not implementation) well started by end of the year, don't you think? :-)

**Comment by astorije** [comment]
Forgot to mention @spencerthayer here, as he mentioned a plugin system on https://github.com/erming/shout/issues/301. Maybe he'll want to stay in touch and maybe give his point of view once requirements start to be written down :-)

**Comment by spencerthayer** [comment]
@astorije certainly interested.

**Comment by olivierlambert** [comment]
Hi,

I'm okay for driving this discussion :) Here is my way of seeing this:

* I'll try to avoid any technical choices on my side. But I will ask sometimes why this or that. I need to understand the global picture.
* "Start small but release often" is my motto.
* I'll promote at max every stuff that help people to enter the project.
* Nothing much to say about the git workflow here, seems fine
* Don't fear about adding more contributors on the repo.

Let's do this.

**Comment by olivierlambert** [comment]
@astorije can you add me as a contributor? thx!
