### ISSUE TITLE
Update CHANGELOG.md on new release

### ISSUE THREAD

**Issue by floogulinc** [erming/shout#521]
0.52.0 was just released without an update to [CHANGELOG.md](https://github.com/erming/shout/blob/master/CHANGELOG.md)

**Comment by astorije** [comment]
The question is: do we want to keep the CHANGELOG.md file or switch to using [GitHub's releases](https://github.com/erming/shout/releases)? Both have pros and cons...

**Comment by floogulinc** [comment]
We are currently using both at Shuo. https://github.com/Shuo-IRC/Shuo/releases

**Comment by JocelynDelalande** [comment]
I would be more in favor of keeping CHANGELOG.md, 

pros:

- it's simple and stupid, 
- it's nice looking
- it's platform independent (GH) and travels with the code

cons:

- it's a bit more of manual work at each release (but it remains reasonable, `git log --oneline` + some filtering does the job quickly)

Packages hosting is already done at NPM, so I don't see great value in GH hosting zip/tar.gz for each version.

**Comment by floogulinc** [comment]
I don't think we have even been using the command for Shuo and have been writing them out by hand and copying it to the release.

**Comment by Xe** [comment]
i've been using `git log`.

**Comment by astorije** [comment]
Closing this as it seems like there is an agreement to edit CHANGELOG.md. Then copy to releases. Do not forget to replicate to releases if people open PRs on the CHANGELOG.

**Comment by astorije** [comment]
I'll write a CHANGELOG entry for 0.52.0 based on what I just did for 0.53.0.

**Comment by JocelynDelalande** [comment]
thanks a lot for realese :)
