### ISSUE TITLE
demo is giving a gateway timeout

### ISSUE THREAD

**Issue by anarcat** [erming/shout#538]
the demo seems to be crashed, which makes it impossible to see how shout looks or works (or rather, it leads me to believe it *doesn't* work... :)

http://demo.shout-irc.com/

> 504 Gateway Time-out
> 
> nginx/1.4.6 (Ubuntu)

**Comment by nickel715** [comment]
duplicate of #529 ?

**Comment by anarcat** [comment]
yes.

**Comment by erming** [comment]
Thanks!
I've fixed it now.
