### ISSUE TITLE
Add shout to docker

### ISSUE THREAD

**Issue by furier** [erming/shout#54]

**Comment by mishak87** [comment]
Hi how is it going?
Could I be of any help? I got experience with docker, just based home server on docker-only setup and shout looks like superb IRC client to have there.

I would like to use official distribution packed by automated builds.

For docker image it needs more ENV parameters with reasonable defaults, but there sed with init script can come to rescue.

**Comment by prologic** [comment]
Let's get this merged and published to the hub already!

**Comment by flaccid** [comment]
+1

**Comment by astorije** [comment]
This was added to Shout, closing this issue.
