### ISSUE TITLE
Nickserv

### ISSUE THREAD

**Issue by Tythus** [erming/shout#546]
maybe I didn't notice it (a very good chance) but I didn't see an ability for me to put in an auto message for nickserv incase of disconnects etc

**Comment by rvschuilenburg** [comment]
It's there, but it's just not part of the UI. You're going to have to edit your user.json in order to achieve that. Check out http://shout-irc.com/docs/server/users.html
For each network you can set up some commands to be executed upon connect.

**Comment by Tythus** [comment]
awesome thanks for your time
