### ISSUE TITLE
When changing channel topic, included links are not linkified

### ISSUE THREAD

**Issue by jancborchardt** [erming/shout#551]
If you change the channel topic with a message which include links, they are not correctly linkified.

Only after a manual refresh it works.

**Comment by astorije** [comment]
Hey @jancborchardt, good catch! Do you think you might want to work on a PR for this? :-)
That would be greatly appreciated!

**Comment by jancborchardt** [comment]
@astorije as much as I’d like to, I’m mainly a HTML/CSS person and can only do basic JS. :)

**Comment by astorije** [comment]
OK well, if someone wants to jump in and give a hand, I don't think this would be too difficult :-)
Adding the **quick and easy** label if newcomers pass by.

**Comment by xPaw** [comment]
Should be fixed by #587

**Comment by astorije** [comment]
Fixed by #587.
