### ISSUE TITLE
Does shout support XDCC?

### ISSUE THREAD

**Issue by imthenachoman** [erming/shout#560]
I'm just wondering if Shout supports XDCC?

**Comment by Xe** [comment]
No

**Comment by imthenachoman** [comment]
@Xe : Thanks!

**Comment by astorije** [comment]
Hi @imthenachoman,

Confirming what @Xe said, there are no support at the moment or in the works. However, some of us are thinking of a plugin system (see #554) , that would let people come up with such features without affecting the program itself.
