### ISSUE TITLE
Failure after ECONNRESET error - possibly due to netsplit

### ISSUE THREAD

**Issue by matthew-lake** [erming/shout#565]
I've experienced this several times - the program encounters a ECONNRESET error, and attempts to send or receive messages fail. Previous messages remain visible, and the problem is only apparent to the user when trying to send a message. Here is a typical output:

```
Shout is now running on http://0.0.0.0:9000/
Press ctrl-c to stop

User 'mgtlake' loaded.
Client#connect():
Error: read ECONNRESET
Client#connect():
Error: write after end
Client#connect():
Error: write after end
Client#connect():
Error: write after end
```
For reference, this is running on Ubuntu on AWS. 

Terminating and restarting the program fixes this issue, but it reoccurs for me about once a week.

**Comment by matthew-lake** [comment]
It has happened again, and it seems that it's being caused by a netsplit occuring in one of the channels I'm connected

**Comment by Xe** [comment]
networks*

**Comment by JocelynDelalande** [comment]
@matthew-lake would you agree it's a duplicate of #235  ?

**Comment by matthew-lake** [comment]
@JocelynDelalande seems like it - I'll close this one then
