### ISSUE TITLE
Display actions (such as join/leave/nick change) differently

### ISSUE THREAD

**Issue by xPaw** [erming/shout#577]
It's confusing to display them same as normal messages.

Here's how it's done in HexChat for example:
![hexchat_xpaw_ _holmes_freenode__ steamdb_2016-01-11_13-39-21](https://cloud.githubusercontent.com/assets/613331/12232623/c48e2e4e-b868-11e5-849d-4ed9bf304ff5.png)

**Comment by astorije** [comment]
For me (default theme), the "join" and "quit" messages are displayed in a very light gray, so not like normal messages. Maybe we could make this even better?
Feel free to suggest things here and if we can reach to a simple consensus, maybe you could open a PR :P

Thanks for the report!

**Comment by dgw** [comment]
The main issue I see with the presentation of join/part/quit/nick events is that they follow an identical line format. Being light gray just makes them hard to read; they still look like talking.

For example, here is how my theme for Textual displays various events:
![image](https://cloud.githubusercontent.com/assets/164140/12286731/e44c96f8-b994-11e5-91c4-e3b71b6cf101.png)

The non-speech events are all a different size, color, and line layout.

**Comment by xPaw** [comment]
Yeah, simply changing color is not enough. @dgw's Textual screenshot is how it should be implemented.
