### ISSUE TITLE
Parse 16-31 irc color range

### ISSUE THREAD

**Issue by xPaw** [erming/shout#583]
Shout simply displays these as a number, but other clients map them to colors. Here's a mapping from hexchat: https://github.com/hexchat/hexchat/blob/78486b49d5b688ba5054631b849f8959846cf07b/src/fe-gtk/palette.c#L59

It's rather hard to find consistent information on this, but it would be better to map these colors into same as 1-15, instead of ignoring them.

**Comment by megawac** [comment]
@xPaw if you're interested you can update this number https://github.com/erming/shout/blob/master/client/js/libs/handlebars/parse.js#L84
and add the css
https://github.com/erming/shout/blob/master/client/css/style.css#L968

**Comment by xPaw** [comment]
I'm thinking this can be directly mapped without adding css classes by doing `(i % 15)` or something along these lines.
