### ISSUE TITLE
Long channel name can overlap the unread counter and close button

### ISSUE THREAD

**Issue by xPaw** [erming/shout#585]
![2016-01-16_19-12-59](https://cloud.githubusercontent.com/assets/613331/12373541/2dc7b27a-bc85-11e5-982d-b65d0e2b6325.png)

**Comment by astorije** [comment]
I believe there are a few open PRs regarding this issue. I haven't looked at them yet so I can't confirm they fix this exact problem but they might. I'll flag this as a bug meanwhile. Thanks!

**Comment by xPaw** [comment]
Fixed in lounge.
