### ISSUE TITLE
Make "msg" packet support multiple messages and remove "more" packet

### ISSUE THREAD

**Issue by xPaw** [erming/shout#594]
Doing so will mean messages loaded from history are processed exactly as newly incoming messages. (links/channels are parsed correctly, etc.). But to support this, "msg" message needs to be able to accept multiple messages, and then know how to insert them into DOM based on time the message was sent.

**Comment by YaManicKill** [comment]
I think that's a sensible way to deal with messages anyway, as there could be a race condition with messages the way they currently work.

**Comment by xPaw** [comment]
This would go nicely with `server-time` extension: http://ircv3.net/specs/extensions/server-time-3.2.html

**Comment by astorije** [comment]
@xPaw, doing so will also make #588 (and others) better when reloading or loading logs, correct?
Do you want to give a try at this?
