### ISSUE TITLE
Invite messages don't show channel

### ISSUE THREAD

**Issue by YaManicKill** [erming/shout#625]
"X invited Y into the channel" <-- you get this in the lobby, and it doesn't say what channel.

It would be good to either show the message in the channel itself, or to say

"X invited Y into the channel (#shout-irc)"

**Comment by MaxLeiter** [comment]
I believe this is an upstream slate-irc issue

**Comment by astorije** [comment]
In terms of IRC, when you invite someone, is it something everyone on a channel see? If yes then it should be displayed in the channel, if not then lobby indeed.

**Comment by xPaw** [comment]
> In terms of IRC, when you invite someone, is it something everyone on a channel see? If yes then it should be displayed in the channel, if not then lobby indeed.

In my experience is way too easy to miss invites, I would suggest opening a new chat window with the user that invited you and displaying it there. However this discussion is unrelated to the bug report itself.

**Comment by YaManicKill** [comment]
Yeah, so the other guys noted that this doesn't show for them. So this is a znc issue. I'll close it.

**Comment by dgw** [comment]
I really don't think it's a ZNC issue. I see the channel name just fine when using ZNC with Textual, for example, and invites are sent to a channel I'm in.

**Comment by TheSonAlsoRises** [comment]
I can confirm it is not a ZNC issue. I am using shout and I get the generic "X invited Y into the channel." in the server window, without any indication of the relevant channel.

**Comment by YaManicKill** [comment]
Alright, I'll reopen then, and we can look into it later. If we aren't explicitly dealing with them, that's probably why it isn't showing correctly.

**Comment by xPaw** [comment]
I don't know how you guys could see invite stuff at all, but invite event wasn't handled at all.
