### ISSUE TITLE
Not working when being proxied by Apache

### ISSUE THREAD

**Issue by KuchenKerze** [erming/shout#661]
Hi,

the app is not working when an existing Apache is configured to proxy all request to it:

> ProxyPreserveHost On
> ProxyPass /shout http://0.0.0.0:8085 
> ProxyPassReverse /shout http://0.0.0.0:8085

It then tries to load resources from the domains root like that:
https://domain.tld/css/bootstrap.css

That does not work because the required resource residents under:
https://domain.tld/shout/css/bootstrap.css

A possible solution would be adding the base URL to the configuration or startup parameters and add this URL to all require statements.

**Comment by YaManicKill** [comment]
This is an issue that has been fixed by thelounge if this is a requirement
for you. Feel free to come check us out, development on shout has basically
stopped.
