### ISSUE TITLE
Passwords as a per-user thing, not a per-server thing.

### ISSUE THREAD

**Issue by AGausmann** [erming/shout#677]
This is kind of related to #359, but it should also be its own issue. 

Nowadays a lot of IRC server and client software recognize the password field as something that a user uses to authenticate himself. For example, freenode forwards the PASS option to NickServ, and Kiwi allows the user to change the password field even when server connection settings are locked. 

Shout currently handles the password field as a "network setting" as if the password is a mandatory field needed to access the network. In my opinion, and likely in the opinion of many others, the password field should be specified as a "user preference", not as a "network setting."

**Comment by astorije** [comment]
@AGausmann, could you open this on [The Lounge](https://github.com/thelounge/lounge) (active, official fork)?
FYI, #359 has been implemented there a while ago: https://github.com/thelounge/lounge/pull/57

**Comment by AGausmann** [comment]
Thanks.
