### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by andrex4k** [erming/shout#682]
It would be desirable to translate) but I didn't find files of localization. To look for the text in scripts?

**Comment by astorije** [comment]
We don't have any current mechanism for internationalization / localization, but it would be great to have one.

If you or anyone would like to contribute to this, feel free to look at the following resources and post ideas / decisions here:
- http://formatjs.io/
- http://ejohn.org/blog/a-strategy-for-i18n-and-node/
- https://github.com/mashpie/i18n-node
- ...

**Comment by andrex4k** [comment]
ok, good)
