### ISSUE TITLE
Please Provide An Automatic Docker Build

### ISSUE THREAD

**Issue by daamien** [erming/shout#687]
Thanks for this great software and for the Dockerfile !

I read the docker deployment process here :
http://shout-irc.com/docs/deployment/docker.html

I think you could simplify the process by providing an automatic build from `hub.docker.com`:

Here's an example:
https://hub.docker.com/r/daamien/shout/

Once you configure the automatic build at `hub.docker.com` , we can skip the first 3 steps of the guide and simply launch

```
docker run --name=shout --publish=9000:9000 --detach --tty shout-img -t erming/shout
```

The image will be fetch the image directly from  `hub.docker.com` 

You can also have a docker image for each branch, for instance  `erming/shout:latest` for master and `erming/shout:dev` for the dev branch

**Comment by MaxLeiter** [comment]
Hey! shouts currently inactive, so I recommend checking out the official fork The Lounge - you can see the docker container here: https://github.com/thelounge/docker-lounge

**Comment by daamien** [comment]
ok thanks
