### ISSUE TITLE
Reloads all logs messages after rebooting Shout IRC

### ISSUE THREAD

**Issue by leopck** [erming/shout#689]
Currently Shout IRC has the ability to log all messages thanks to PR #29 however, Shout IRC requires restarting from time to time (at least for my case) and after restarting all of my history inside the website disappears. 

Thankfully, it is all stored into logs however, I would love to see all my logs reloads back into the website. Rather than just a text file inside my server. This is also not desirable for multi-user configurations as I can
t provide access to other users as other users would be able to access other user's log files.

I hope to see the ability of reloading all the log text files back into the website after each reboot.

**Comment by MaxLeiter** [comment]
Hey leopck, just a note that shout is outdated and has been succeeded by https://github.com/thelounge/Lounge. While it doesn't load message from logs or a database after a restart (same issue as Shout), efforts are being made - see https://github.com/thelounge/lounge/pull/663 and https://github.com/thelounge/lounge/pull/506

If you have any questions feel free to stop by in #thelounge on freenode.

**Comment by leopck** [comment]
alright thanks!
