### ISSUE TITLE
Demo link is distributing malware

### ISSUE THREAD

**Issue by jamesgecko** [erming/shout#698]
The "Try the Demo" link currently redirects to several different sites that try to trick the user into installing malware.

- - -

# Chrome extension

![Screen Shot 2020-08-27 at 1 50 50 PM](https://user-images.githubusercontent.com/44252/91477539-7da07080-e86c-11ea-8608-ee59c9d64733.png)
![Screen Shot 2020-08-27 at 1 51 00 PM](https://user-images.githubusercontent.com/44252/91477542-7ed19d80-e86c-11ea-9721-ac7cbe8f7274.png)

- - -

# System update

![Screen Shot 2020-08-27 at 1 51 42 PM](https://user-images.githubusercontent.com/44252/91477558-83965180-e86c-11ea-9d85-d7de33c2131b.png)

**Comment by dgw** [comment]
Eesh, I guess the domain expired and got poached by scammers/squatters. Hopefully someone still active on GitHub has push access to remove the links to that domain no longer controlled by the project.

**Comment by erming** [comment]
@jamesgecko: Thanks for reporting this! I'm not very active here, but @MaxLeiter saw the issue and threw an email in my direction. As @dgw says, the URL got squatted after I stopped paying for it

I've now removed any trace of the URL and pushed the changes

Thanks guys!
