### ISSUE TITLE
Server command at connection

### ISSUE THREAD

**Issue by toxinu** [erming/shout#78]
It could be nice to have a `command` for `servers` configuration in order to run specific command at server connection like for Freenode auth.

This is how you configure it in weechat for example:

`/set irc.server.freenode.command "/msg nickserv identify xxxxxxx"`

Something like that in `shout` configuration file: 

```
[...]
 "networks": [{
    "host": "irc.freenode.org",
    "port": 6667,
    "nick": "socketubs",
    "realname": "socketubs",
    "join": "#shout-irc",
    "command": "/msg NickServ identify <password>"
  }]
[...]
```

**Comment by Porco-Rosso** [comment]
Hi, The example link no longer works. 
It would be great if this could be documented in the wiki, as I am having trouble setting it up!

For example, I don't understand, will the command be sent anytime I join the listed network? or will it automatically join the network when logging in/starting shout?

Thanks!

**Comment by MaxLeiter** [comment]
Hey, shouts currently outdated - id check out The Lounge http://www.github.com/thelounge/lounge

**Comment by Porco-Rosso** [comment]
oops, I thought this issue was on the lounge repo. 
Sorry, and thanks!
