### ISSUE TITLE
Sticky Topics

### ISSUE THREAD

**Issue by jimmyxander** [erming/shout#91]
Having the topic fixed to the top of the chat window is a nice feature. I know a lot of other clients do it, but it's really nice to have, specially since a lot of topics offer useful links.

**Comment by kalaksi** [comment]
Apparently this was already implemented but disabled again because of a XSS vulnerability.
I have made a fix and a PR: https://github.com/erming/shout/pull/409

**Comment by xPaw** [comment]
It appears that this is fixed.

**Comment by astorije** [comment]
Correct, thanks!
